<?php
// Votes des 4 nouveaux participants Frama (Aude, Alice, Marie, Cécile),
// extraits verbatim du sondage https://beta.framadate.org/polls/9486ec5e108fe91cec98
// Format : [Nom][YYYY-MM-DD][label-créneau] => 'yes' | 'no' | 'maybe'  (null = pas dans le tableau)
return [
    'Aude' => [
        '2026-05-26' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'no'],
        '2026-05-27' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'no'],
        '2026-05-28' => ['Journée' => 'yes',   'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-01' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'maybe'],
        '2026-06-02' => ['Journée' => 'yes',   'Soirée' => 'maybe', 'Nuit' => 'maybe'],
        '2026-06-03' => [                      'Soirée' => 'yes',   'Nuit' => 'maybe'],
        '2026-06-04' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'maybe'],
        '2026-06-05' => ['Journée' => 'maybe', 'Soirée' => 'maybe', 'Nuit' => 'maybe'],
        '2026-06-06' => ['Journée' => 'maybe', 'Soirée' => 'maybe', 'Nuit' => 'maybe'],
        '2026-06-07' => ['Journée' => 'maybe', 'Soirée' => 'maybe', 'Nuit' => 'maybe'],
        '2026-06-08' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-09' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-10' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-11' => ['Journée' => 'yes',   'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-12' => ['Journée' => 'yes',   'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-13' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-14' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-15' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-16' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-17' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-18' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-19' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'maybe'],
        '2026-06-20' => ['Journée' => 'yes',   'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-21' => [                      'Soirée' => 'maybe', 'Nuit' => 'maybe'],
        '2026-06-22' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-23' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-24' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-25' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-26' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
    ],
    'Alice' => [
        '2026-05-26' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-05-27' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-05-28' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-05-29' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-05-30' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-05-31' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-01' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-02' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'yes'],
        '2026-06-03' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-04' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-05' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-06' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-07' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-08' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-09' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'yes'],
        '2026-06-10' => ['Journée' => 'yes', 'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-11' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-12' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-13' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-14' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-15' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-16' => ['Journée' => 'yes', 'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-17' => ['Journée' => 'yes', 'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-18' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-19' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-20' => ['Journée' => 'no',  'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-21' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-22' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-23' => ['Journée' => 'yes', 'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-24' => ['Journée' => 'yes', 'Soirée' => 'no',  'Nuit' => 'no'],
        '2026-06-25' => ['Journée' => 'yes', 'Soirée' => 'yes', 'Nuit' => 'yes'],
        '2026-06-26' => ['Journée' => 'no',  'Soirée' => 'no',  'Nuit' => 'no'],
    ],
    'Marie' => [
        '2026-05-26' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-05-27' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-05-28' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-05-29' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'no'],
        '2026-05-30' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-05-31' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-01' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-02' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-03' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-04' => ['Journée' => 'no',    'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-05' => ['Journée' => 'yes',   'Soirée' => 'maybe', 'Nuit' => 'no'],
        '2026-06-06' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-07' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-08' => ['Journée' => 'yes',   'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-09' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-10' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-11' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-12' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-13' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-14' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-15' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-16' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-17' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-18' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-19' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-20' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-21' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-22' => ['Journée' => 'no',    'Soirée' => 'yes',   'Nuit' => 'yes'],
        '2026-06-23' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-24' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-25' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
        '2026-06-26' => ['Journée' => 'no',    'Soirée' => 'no',    'Nuit' => 'no'],
    ],
    'Cécile' => [
        '2026-06-19' => ['Journée' => 'yes'],
        '2026-06-20' => ['Journée' => 'yes'],
        '2026-06-21' => ['Journée' => 'yes'],
        '2026-06-23' => ['Journée' => 'yes'],
        '2026-06-24' => ['Journée' => 'yes'],
        '2026-06-25' => ['Journée' => 'yes'],
    ],
];
